### ISSUE TITLE
ReferenceError: oneProduction is not defined

### ISSUE THREAD

**Issue by Veronesi** [Veronesi/NodeCompiler#1]
Código a compilar 
```js
a = 5
```

Mensaje de error:

```
<Asignacion>
├──ID 'a'
├──OPERADORASIGNACION '='
└──<Expresion>
   └──<ExpresionAritmetica>
      ├──NUMERO '5'
      └──<ExpresionAritmeticaFinal>
********Verficiamos que sean generados por el nodo raiz**********
position of index: 0
(node:9864) UnhandledPromiseRejectionWarning: ReferenceError: oneProduction is not defined
    at newsRoots.forEach.newsProduccion (D:\git\NodeCompiler\src\tools\AnalisisSintactico.js:365:85)
    at Array.forEach (<anonymous>)
    at producciones.filter.e (D:\git\NodeCompiler\src\tools\AnalisisSintactico.js:363:35)
    at Array.filter (<anonymous>)
    at AnalisisSintactico.rootearProduccion (D:\git\NodeCompiler\src\tools\AnalisisSintactico.js:357:34)
    at produccion.forEach.e (D:\git\NodeCompiler\src\tools\AnalisisSintactico.js:472:22)
    at Array.forEach (<anonymous>)
    at AnalisisSintactico.start (D:\git\NodeCompiler\src\tools\AnalisisSintactico.js:471:29)
    at analisisLexico.start.tokens (D:\git\NodeCompiler\src\index.js:59:36)
    at AnalisisLexico.start (D:\git\NodeCompiler\src\tools\AnalisisLexico.js:201:13)
(node:9864) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9864) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Veronesi** [comment]
https://github.com/Veronesi/NodeCompiler/commit/f1f93e6fd3159b0b1b9511556f266734b8d7b78f#diff-a4fc96993f4b9621e9bad8e2bc827116L357-L360

Se estaba utilizando en una parte del codigo el nombre de variable **e** y luego **oneProduction**
